### ISSUE TITLE
Choose and implement the basics of a UI framework

### ISSUE THREAD

**Issue by misterpeddy** [misterpeddy/hands-down#2]
I'm not well versed in today's hottest frameworks. 
The following requirements come to mind:

* Must be lightweight in terms of code (it shouldn't take over the project source tree and be super opinionated about how things should be laid out)
* Must be lightweight in terms of amount of stuff we're adding to the site that we send to clients
* This will most likely be a single-page application
* Shouldn't have to invest too much time into it since we might consider building the chrome extension as well (to which any effort that goes into this will be irrelevant)

**Comment by Berkmann18** [comment]
Some ideas (although I haven't tried any _with_ Tensorflow.js so I don't know yet how well it plays out with certain types of view rendering) I have would be:
- Static Site Generators: Gridsome/Nuxt Gen, Gatsby, or Scully (although it might not be lightweight due to its Angular dependence)
- Server-Side Renders: Nuxt, Next, Nest
- Dynamic: VueJS, React (not a framework but a viable option nonetheless)
- Others: SvelteJS

In conjunction with the above we could use:
- TypeScript or stick with JS (say ES9-10) for logic
- SCSS/Sass or stick with CSS3 for styling

**Comment by amirhmk** [comment]
Just some initial thoughts, we probably don't need to go for a React/Vue app sort of territory, as it's a pretty app and may be an overkill. Though I can certainly see those frameworks to come in handy once we have way more features (Now I can only think of ML Models, camera, extracting that info, inference using that info and drawing it out, statistics page)

Right now all of those things are pretty much there with the current setup, so it's only the stats page that is left. After a quick look around, [http://getskeleton.com](url) looks like a good options:
1- Extremely lightweight
2- Has basic UI essentials (Grid, Buttons, Tables, etc)
