### ISSUE TITLE
Explore explicitly setting media frame rate 

### ISSUE THREAD

**Issue by misterpeddy** [misterpeddy/hands-down#40]

**Comment by Berkmann18** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#Frame_rate

So possibly something like:
```diff
const stream = await navigator.mediaDevices.getUserMedia({
      video: {
        facingMode: 'user',
+      frameRate: { ideal: 20, max: 30 }
        ...computeCameraDimensions(),
      },
      audio: false,
    });
```

**Comment by Berkmann18** [comment]
Since it's not possible to (unless there's some hacks) to change the video's `frameRate` after the `getUserMedia` call, it would be worth getting the backend initialisation to happen first; this way, a more ideal frame rate could be set based on the backend.
I've got something promising so far. (see linked PR).
